language: java

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

script:
 - "mvn cobertura:cobertura"

before_install:
  - export PATH=$PATH:$HOME/.local/bin

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
